# Generated by Django 3.0.6 on 2020-05-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=256)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
